appium:
  app: ""
  url: http://127.0.0.1:4723/wd/hub
  wait: 6
  capabilities:
    platformName: android
    deviceName: dddd
    appPackage: com.xueqiu.android
    appActivity: .view.WelcomeActivityAlias
    autoGrantPermissions: true

data:
  selectinput:
    - suning
    - liantong
  selectresult:
    - 苏宁易购
    - 中国联通